// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCZg2-Jt1wNM6HaX7vOkzNSK3NM768_2Fo',
    appId: '1:170932593726:web:abddc1972c98e6ea7a5d6f',
    messagingSenderId: '170932593726',
    projectId: 'budget-app-test-c53df',
    authDomain: 'budget-app-test-c53df.firebaseapp.com',
    storageBucket: 'budget-app-test-c53df.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCnQNgmogyei-rUCexM7wrDzxAwbSwfbCA',
    appId: '1:170932593726:android:037f916dc68b02297a5d6f',
    messagingSenderId: '170932593726',
    projectId: 'budget-app-test-c53df',
    storageBucket: 'budget-app-test-c53df.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyC1WJ0BSChrU7GW3SXLhXbBtkPwtzUHrAQ',
    appId: '1:170932593726:ios:7bf3d171c60f1e3a7a5d6f',
    messagingSenderId: '170932593726',
    projectId: 'budget-app-test-c53df',
    storageBucket: 'budget-app-test-c53df.firebasestorage.app',
    iosBundleId: 'com.example.projetFlutter',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyC1WJ0BSChrU7GW3SXLhXbBtkPwtzUHrAQ',
    appId: '1:170932593726:ios:7bf3d171c60f1e3a7a5d6f',
    messagingSenderId: '170932593726',
    projectId: 'budget-app-test-c53df',
    storageBucket: 'budget-app-test-c53df.firebasestorage.app',
    iosBundleId: 'com.example.projetFlutter',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCZg2-Jt1wNM6HaX7vOkzNSK3NM768_2Fo',
    appId: '1:170932593726:web:3d02bf01b498d7977a5d6f',
    messagingSenderId: '170932593726',
    projectId: 'budget-app-test-c53df',
    authDomain: 'budget-app-test-c53df.firebaseapp.com',
    storageBucket: 'budget-app-test-c53df.firebasestorage.app',
  );

}